# .streamlit/secrets.toml

[api_keys]
fred = "a81e9c33d8dbac1cc1309e51527e0d53"
alpha_vantage = "E3R1QOXBCPW9924S"
polygon = "9rP1CLlxuoRWPvkEiOMxxIwNyffjUEb4"
news = "pub_65773c625d48ffecc8522ad52fe0fd7199cce"

# Optional: Environment-specific configurations
[development]
debug = true
log_level = "DEBUG"

[production]
debug = false
log_level = "INFO"
